# Generated by Django 4.2.4 on 2023-08-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_music', '0002_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_favorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
