# Generated by Django 4.2.4 on 2023-08-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_music', '0005_remove_user_favorites_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_art',
            field=models.ImageField(blank=True, null=True, upload_to='static/album_art/'),
        ),
    ]
